permalink: /:year/:month/:title:output_ext

plugins:
  - jekyll-paginate

# Pagination Settings
pagination:
  enabled: true
  per_page: 10
  permalink: '/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
